import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lip/utils";
import { ThemeProvider } from "@/components/ui/theme-provdier";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", geist.variable)}
    >
      <body
        className={cn(
          "min-h-screen bg-dark-300 font-sans antialiased",
          geist.variable,
        )}
      >
        {/* <ThemeProvider attribute="class" defaultTheme="dark">
          {children}
        </ThemeProvider> */}
        {children}
      </body>
    </html>
  );
}
